# Lokale Entwicklung (Keycloak + MinIO + MongoDB via Docker Compose)

# MongoDB
spring.data.mongodb.uri=mongodb://root:example@localhost:27018/social?authSource=admin

# OIDC (Keycloak lokal)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/social
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/realms/social/protocol/openid-connect/certs

# S3 (MinIO lokal)
s3.endpoint=http://localhost:9000
s3.access-key=lukas
s3.secret-key=example1
s3.bucket=social
s3.region=eu-central-1

# Logging
logging.level.org.springframework.security=INFO

# Web Push (VAPID) - generated dev keys
vapid.public-key=BJGbfB_Pu3zpxuk9I3B7D58CZCadkrIjWDbMj8ju6jQEE9EQ8x9Sfjcb6iloPuPge3ngmTdCblwAzRH9abGrAyU
vapid.private-key=lwMcj1ewAAbFPFF2jrArPR726APwJL4iVyt6MAMGvys
